name: build-windows-exe
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pdfminer.six pymupdf pytesseract pyinstaller Pillow

      - name: Install Tesseract via Chocolatey
        run: choco install tesseract -y

      - name: Vendorize Tesseract binaries
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path vendor\tesseract | Out-Null
          Copy-Item "$Env:ProgramFiles\Tesseract-OCR\*" vendor\tesseract -Recurse

      - name: Include tessdata (eng + spa) in bundle
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path vendor\tesseract\tessdata | Out-Null
          Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata" -OutFile "vendor\tesseract\tessdata\eng.traineddata"
          Invoke-WebRequest -Uri "https://github.com/tesseract-ocr/tessdata/raw/main/spa.traineddata" -OutFile "vendor\tesseract\tessdata\spa.traineddata"
          Write-Host "Bundled tessdata:"; Get-ChildItem vendor\tesseract\tessdata | Select-Object Name,Length

      - name: Build exe
        run: |
          pyinstaller --onefile --name extrae_tel_pdf --add-data "vendor\\tesseract;tesseract" extrae_tel_pdf_ocr.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extrae_tel_pdf_exe
          path: dist\extrae_tel_pdf.exe
